'use client';
import {useEffect,useLayoutEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {FileText,Download,Mail,Phone,MapPin,GitFork,Globe,GraduationCap,Briefcase,Code,Award,Calendar,User,Plus,Minus,Check,Bold,List,Heading2,Sparkles} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {ResizablePanelGroup,ResizablePanel,ResizableHandle} from '@/components/ui/resizable';
import {initialResume} from './sample';
function XiaomiIcon({className='',size=17}:{className?:string;size?:number}){return <img src="/icons/xiaomi.svg" alt="小米" width={size} height={size} className={className}/>;}
function MomentaIcon({className='',size=17}:{className?:string;size?:number}){return <img src="/icons/momenta.png" alt="Momenta" width={size*8.3} height={size} className={`${className} brand-momenta`}/>;}
const icons={mail:Mail,phone:Phone,location:MapPin,github:GitFork,globe:Globe,education:GraduationCap,work:Briefcase,code:Code,award:Award,calendar:Calendar,user:User,xiaomi:XiaomiIcon,momenta:MomentaIcon};
const labels:Record<string,string>={mail:'邮箱',phone:'电话',location:'位置',github:'GitHub',globe:'网站',education:'教育',work:'工作',code:'技能',award:'荣誉',calendar:'日期',user:'个人',xiaomi:'小米',momenta:'Momenta'};
function parse(source:string){return source.split('\n').filter(x=>x.trim()).flatMap(line=>{for(const [prefix,kind] of [['### ','entry'],['## ','section'],['# ','name']])if(line.startsWith(prefix))return [{kind,text:line.slice(prefix.length)}];const kind=line.startsWith('- ')?'bullet':'text';return (kind==='bullet'?line.slice(2):line).match(/[\s\S]{1,350}/g)?.map(text=>({kind,text}))??[];});}
function Inline({text,show}:{text:string;show:boolean}){return <>{text.split(/(\*\*[^*]+\*\*|`[^`]+`|:[a-z]+:)/g).map((p,i)=>{if(p.startsWith('**'))return <strong key={i}>{p.slice(2,-2)}</strong>;if(p.startsWith('`'))return <code key={i}>{p.slice(1,-1)}</code>;const key=p.slice(1,-1);const Icon=Object.hasOwn(icons,key)?icons[key as keyof typeof icons]:undefined;if(Icon&&p.startsWith(':'))return show?<Icon key={i} className="resume-icon" aria-label={labels[p.slice(1,-1)]}/>:null;return p;})}</>;}
function Block({block,show}:{block:{kind:string;text:string};show:boolean}){const [left,...right]=block.text.split(' | ');const content=<><span><Inline text={left} show={show}/></span>{right.length>0&&<span className="right-date"><Inline text={right.join(' | ')} show={show}/></span>}</>;if(block.kind==='name')return <h1 className="r-block r-name">{content}</h1>;if(block.kind==='section')return <h2 className="r-block r-section">{content}</h2>;if(block.kind==='entry')return <h3 className="r-block r-entry">{content}</h3>;return <div className={`r-block r-${block.kind}`}>{content}</div>;}
export default function Home(){
 const [source,setSource]=useState(initialResume),[fontSize,setFontSize]=useState(13.5),[leading,setLeading]=useState(1.4),[show,setShow]=useState(true),[zoom,setZoom]=useState(85),[pages,setPages]=useState<{kind:string;text:string}[][]>([]),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[saved,setSaved]=useState(false);
 const [iconHeight,setIconHeight]=useState(14),[momentaHeight,setMomentaHeight]=useState(9);
 const editor=useRef<HTMLTextAreaElement>(null),measure=useRef<HTMLDivElement>(null);const blocks=useMemo(()=>parse(source),[source]);const style={'--resume-size':`${fontSize}px`,'--resume-leading':leading,'--icon-height':`${iconHeight}px`,'--momenta-height':`${momentaHeight}px`} as CSSProperties;
 useEffect(()=>{try{const raw=localStorage.getItem('liveresume-v1');if(raw){const d=JSON.parse(raw);if(typeof d.source==='string')setSource(d.source);if(d.fontSize>=11&&d.fontSize<=17)setFontSize(d.fontSize);if(d.leading>=1.2&&d.leading<=1.8)setLeading(d.leading);if(typeof d.show==='boolean')setShow(d.show);if(Number.isFinite(d.iconHeight)&&d.iconHeight>=8&&d.iconHeight<=28)setIconHeight(d.iconHeight);if(Number.isFinite(d.momentaHeight)&&d.momentaHeight>=6&&d.momentaHeight<=20)setMomentaHeight(d.momentaHeight);}}catch{setNotice('无法读取本机草稿，可继续编辑。');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;setSaved(false);const t=setTimeout(()=>{try{localStorage.setItem('liveresume-v1',JSON.stringify({source,fontSize,leading,show,iconHeight,momentaHeight}));setSaved(true);}catch{setNotice('本机存储不可用，请保持页面打开并及时导出。');}},500);return()=>clearTimeout(t);},[source,fontSize,leading,show,iconHeight,momentaHeight,ready]);
 useLayoutEffect(()=>{let active=true;const paginate=()=>{if(!active||!measure.current)return;const nodes=Array.from(measure.current.children) as HTMLElement[];const result:{kind:string;text:string}[][]=[[]];let height=0;nodes.forEach((node,i)=>{const h=node.getBoundingClientRect().height,next=nodes[i+1]?.getBoundingClientRect().height??0;const needed=h+(['section','entry'].includes(blocks[i].kind)?next:0);if(height+needed>1033&&result[result.length-1].length){result.push([]);height=0;}result[result.length-1].push(blocks[i]);height+=h;});setPages(result);};paginate();document.fonts.ready.then(paginate);return()=>{active=false;};},[blocks,fontSize,leading,show,iconHeight,momentaHeight]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'replace_resume_content',title:'更新简历内容',description:'Replace the editor Markdown and refresh the resume preview. Saves to this browser.',inputSchema:{type:'object',properties:{markdown:{type:'string',maxLength:50000}},required:['markdown'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const data=input as {markdown?:unknown};if(!data||typeof data.markdown!=='string'||data.markdown.length>50000)throw new Error('markdown must be a string of at most 50000 characters');setSource(data.markdown);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {updated:true,characters:data.markdown.length};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 function insert(before:string,after=''){const el=editor.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;setSource(source.slice(0,start)+before+source.slice(start,end)+after+source.slice(end));requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+before.length,end+before.length);});}
 async function printResume(){await document.fonts.ready;document.title=(blocks.find(b=>b.kind==='name')?.text??'我的')+'-简历';setNotice('在打印窗口选择“另存为 PDF”，纸张选择 A4，并关闭页眉和页脚。');window.print();}
 return <main className="workspace"><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><FileText size={21}/></span>LiveResume<span className="beta">简历工作台</span></a><div className="top-actions"><span className="save-state"><Check size={14}/>{saved?'已保存到本机':'编辑中'}</span><button className="export-button" onClick={printResume}><Download size={16}/>导出 PDF</button></div></header>
 <ResizablePanelGroup className="workspace-body" orientation="horizontal"><ResizablePanel id="editor" defaultSize="35%" minSize="320px" className="editor-resizable"><section className="editor-panel" aria-label="简历编辑器"><div className="editor-heading"><div className="eyebrow">YOUR NEXT CHAPTER</div><h1>把经历，写成机会。</h1><p>一边编辑，一边看见你的下一步。</p></div>
 <Tabs defaultValue="content" className="editor-tabs"><TabsList className="tab-list"><TabsTrigger value="content">内容编辑</TabsTrigger><TabsTrigger value="style">排版设置</TabsTrigger></TabsList><TabsContent value="content"><div className="document-label"><span>我的简历 <small>Markdown</small></span><span>{source.length.toLocaleString()} 字符</span></div><div className="writing-tools"><button aria-label="插入加粗" title="加粗" onClick={()=>insert('**','**')}><Bold size={16}/></button><button aria-label="插入章节标题" title="章节标题" onClick={()=>insert('\n## ')}><Heading2 size={19}/></button><button aria-label="插入项目符号" title="项目符号" onClick={()=>insert('\n- ')}><List size={18}/></button><span className="tool-divider"/><span>支持 **加粗** 与图标</span></div><details className="icon-picker" open><summary><Sparkles size={15}/>插入图标<span>13 个图标</span></summary><div className="icon-grid">{Object.entries(icons).map(([key,Icon])=><button key={key} onClick={()=>insert(`:${key}: `)} title={`:${key}:`}><Icon size={17}/>{labels[key]}</button>)}</div></details><textarea ref={editor} spellCheck={false} className="source-editor" aria-label="简历 Markdown 内容" value={source} onChange={e=>setSource(e.target.value)}/><details className="syntax-help"><summary>格式小抄</summary><p># 姓名 · ## 章节 · ### 项目<br/>- 列表 · **加粗** · `技术标签`<br/>使用「空格 | 空格」将日期放在右侧。<br/>图标示例：:mail:、:github:、:xiaomi:、:momenta:</p></details></TabsContent>
 <TabsContent value="style" className="style-panel"><h2>经典单栏</h2><p>沿用参考简历的黑白排版、分区横线与 A4 纸张。</p><div className="setting"><label className="slider-label"><span>正文字号<b>{fontSize} px</b></span><Slider aria-label="正文字号" min={11} max={17} step={0.5} value={[fontSize]} onValueChange={v=>setFontSize(Array.isArray(v)?v[0]:v)}/></label></div><div className="setting"><label className="slider-label"><span>行距<b>{leading.toFixed(2)}</b></span><Slider aria-label="正文行距" min={1.2} max={1.8} step={0.05} value={[leading]} onValueChange={v=>setLeading(Array.isArray(v)?v[0]:v)}/></label></div><div className="switch-row"><label htmlFor="icons-switch">显示简历图标</label><Switch id="icons-switch" checked={show} onCheckedChange={setShow}/></div><div className="setting"><label className="slider-label"><span>图标高度<b>{iconHeight} px</b></span><Slider aria-label="图标高度" min={8} max={28} step={1} value={[iconHeight]} onValueChange={v=>setIconHeight(Array.isArray(v)?v[0]:v)}/></label></div><div className="setting"><label className="slider-label"><span>Momenta 图标高度<b>{momentaHeight} px</b></span><Slider aria-label="Momenta 图标高度" min={6} max={20} step={1} value={[momentaHeight]} onValueChange={v=>setMomentaHeight(Array.isArray(v)?v[0]:v)}/></label><p>横版标志单独调整高度，宽度按原比例缩放。</p></div><div className="paper-note"><FileText size={22}/><div><strong>A4 · 210 × 297 mm</strong><p>内容超出一页时自动分页。字号和行距同步应用于 PDF。</p></div></div></TabsContent></Tabs><footer className="editor-footer"><span className="status-dot"/>草稿仅保存在当前浏览器</footer></section></ResizablePanel><ResizableHandle withHandle className="workspace-divider" aria-label="调整编辑区和预览区宽度" title="拖动调整左右宽度，也可用左右方向键"/><ResizablePanel id="preview" minSize="280px" className="preview-resizable">
 <section className="preview-panel" aria-label="简历实时预览"><div className="preview-toolbar"><div><span className="status-dot"/>实时预览<span className="preview-meta">A4 / {pages.length||1} 页</span></div><div className="zoom-control"><button aria-label="缩小预览" disabled={zoom<=45} onClick={()=>setZoom(z=>z-10)}><Minus size={15}/></button><span>{zoom}%</span><button aria-label="放大预览" disabled={zoom>=115} onClick={()=>setZoom(z=>z+10)}><Plus size={15}/></button></div></div>{notice&&<div className="notice" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}<div className="preview-scroll"><div className="pages" style={{zoom:zoom/100,...style}}>{pages.map((indices,p)=><div key={p}><article className="resume-page"><div className="resume-content">{indices.map((block,i)=><Block key={i} block={block} show={show}/>)}</div></article><div className="page-caption">{p+1} / {pages.length}</div></div>)}</div></div></section></ResizablePanel></ResizablePanelGroup>
 <div ref={measure} className="resume-content measure" style={style} aria-hidden="true">{blocks.map((block,i)=><Block key={i} block={block} show={show}/>)}</div><div className="print-pages" style={style}>{pages.map((indices,p)=><article className="print-page resume-content" key={p}>{indices.map((block,i)=><Block key={i} block={block} show={show}/>)}</article>)}</div></main>;
}


