import {randomUUID} from 'node:crypto';
import {getPool,transaction} from './db.mjs';
export class StorageError extends Error{constructor(status,message){super(message);this.status=status;}}
export function validateResume(r){
 if(!r||typeof r.source!=='string'||r.source.length>200000||typeof r.show!=='boolean'||![[r.fontSize,11,17],[r.leading,1.2,1.8],[r.iconHeight,8,28],[r.momentaHeight,6,20]].every(([n,min,max])=>Number.isFinite(n)&&n>=min&&n<=max))throw new StorageError(400,'简历内容或排版参数无效（正文最多 20 万字符）。');
 return {source:r.source,fontSize:r.fontSize,leading:r.leading,show:r.show,iconHeight:r.iconHeight,momentaHeight:r.momentaHeight};
}
function title(name){if(typeof name!=='string'||!name.trim()||name.trim().length>80)throw new StorageError(400,'快照名称须为 1–80 个字符。');return name.trim();}
function uuid(id){if(typeof id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw new StorageError(400,'快照编号无效。');return id;}
function revision(n){if(!Number.isInteger(n)||n<0)throw new StorageError(400,'草稿版本无效。');return n;}
function row(r){return {id:r.id,name:r.name,resume:r.resume,createdAt:new Date(r.created_at).toISOString()};}
export async function executeStorage(input,workspace=process.env.RESUME_WORKSPACE||'default',db={pool:getPool,transaction}){
 if(input.action==='read'){const pool=db.pool();const [draft,items]=await Promise.all([pool.query('SELECT resume,revision FROM liveresume_drafts WHERE workspace=$1',[workspace]),pool.query('SELECT * FROM liveresume_snapshots WHERE workspace=$1 ORDER BY created_at DESC,id',[workspace])]);return {draft:draft.rows[0]?.resume??null,revision:draft.rows[0]?.revision??0,snapshots:items.rows.map(row)};}
 if(input.action==='saveDraft'){const resume=validateResume(input.resume),expected=revision(input.revision);const result=await db.pool().query(`INSERT INTO liveresume_drafts(workspace,resume,revision) SELECT $1,$2::jsonb,1 WHERE $3::integer=0
 ON CONFLICT(workspace) DO UPDATE SET resume=EXCLUDED.resume,revision=liveresume_drafts.revision+1,updated_at=now() WHERE liveresume_drafts.revision=$3 RETURNING revision`,[workspace,JSON.stringify(resume),expected]);
 // Existing drafts need an UPDATE when the expected version is nonzero.
 if(!result.rowCount&&expected>0){const updated=await db.pool().query('UPDATE liveresume_drafts SET resume=$2::jsonb,revision=revision+1,updated_at=now() WHERE workspace=$1 AND revision=$3 RETURNING revision',[workspace,JSON.stringify(resume),expected]);if(updated.rowCount)return {revision:updated.rows[0].revision};}
 if(!result.rowCount)throw new StorageError(409,'数据库草稿已被其他窗口修改，请先保存当前内容为快照，再刷新页面。');return {revision:result.rows[0].revision};}
 if(input.action==='saveSnapshot'){const resume=validateResume(input.resume),name=title(input.name),id=uuid(input.id);const result=await db.pool().query('INSERT INTO liveresume_snapshots(workspace,id,name,resume) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(workspace,id) DO NOTHING RETURNING *',[workspace,id,name,JSON.stringify(resume)]);return {saved:true,id:result.rows[0]?.id??id};}
 if(input.action==='rename'){const id=uuid(input.id),name=title(input.name);const r=await db.pool().query('UPDATE liveresume_snapshots SET name=$3 WHERE workspace=$1 AND id=$2 RETURNING id',[workspace,id,name]);if(!r.rowCount)throw new StorageError(404,'快照不存在，请刷新列表。');return {renamed:true};}
 if(input.action==='delete'){await db.pool().query('DELETE FROM liveresume_snapshots WHERE workspace=$1 AND id=$2',[workspace,uuid(input.id)]);return {deleted:true};}
 if(input.action==='load'){const id=uuid(input.id),current=validateResume(input.current);return db.transaction(async client=>{const r=await client.query('SELECT * FROM liveresume_snapshots WHERE workspace=$1 AND id=$2 FOR SHARE',[workspace,id]);if(!r.rowCount)throw new StorageError(404,'快照不存在，请刷新列表。');const target=validateResume(r.rows[0].resume);if(JSON.stringify(current)!==JSON.stringify(target))await client.query('INSERT INTO liveresume_snapshots(workspace,id,name,resume) VALUES($1,$2,$3,$4::jsonb)',[workspace,randomUUID(),'加载前自动备份 · '+new Date().toISOString(),JSON.stringify(current)]);return {resume:target};});}
 if(input.action==='import'){if(!Array.isArray(input.snapshots)||input.snapshots.length>500)throw new StorageError(400,'每次最多导入 500 份快照。');const items=input.snapshots.map(s=>({id:uuid(s.id),name:title(s.name),resume:validateResume(s.resume),date:new Date(s.createdAt)}));if(items.some(s=>!Number.isFinite(s.date.getTime())))throw new StorageError(400,'快照时间无效。');const draft=input.draft?validateResume(input.draft):null;return db.transaction(async client=>{let count=0;for(const s of items){const r=await client.query('INSERT INTO liveresume_snapshots(workspace,id,name,resume,created_at) VALUES($1,$2,$3,$4::jsonb,$5) ON CONFLICT(workspace,id) DO NOTHING',[workspace,s.id,s.name,JSON.stringify(s.resume),s.date]);count+=r.rowCount;}if(draft){const digest=(await import('node:crypto')).createHash('sha256').update(JSON.stringify(draft)).digest('hex');const id=`${digest.slice(0,8)}-${digest.slice(8,12)}-${digest.slice(12,16)}-${digest.slice(16,20)}-${digest.slice(20,32)}`;const r=await client.query('INSERT INTO liveresume_snapshots(workspace,id,name,resume) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(workspace,id) DO NOTHING',[workspace,id,'导入的本机草稿',JSON.stringify(draft)]);count+=r.rowCount;}return {imported:count};});}
 throw new StorageError(400,'未知存储操作。');
}
export async function handleStorage(request){
 const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
 try{const url=new URL(request.url);if(!['localhost','127.0.0.1','[::1]'].includes(url.hostname)||request.headers.get('x-liveresume')!=='1'||(request.headers.get('origin')&&request.headers.get('origin')!==url.origin)||request.headers.get('sec-fetch-site')==='cross-site')throw new StorageError(403,'仅允许本机页面访问数据。');
 let input={action:'read'};if(request.method==='POST'){if(!request.headers.get('content-type')?.includes('application/json'))throw new StorageError(415,'需要 JSON 请求。');const reader=request.body?.getReader();let total=0,chunks=[];if(!reader)throw new StorageError(400,'请求不能为空。');while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>8*1024*1024){await reader.cancel();throw new StorageError(413,'请求过大，请分批导入快照。');}chunks.push(value);}try{input=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw new StorageError(400,'JSON 格式无效。');}if(!input||typeof input!=='object')throw new StorageError(400,'请求格式无效。');}
 return json(await executeStorage(input));
 }catch(error){if(error instanceof StorageError)return json({error:error.message},error.status);const message=error?.message==='DATABASE_CONFIG'?'尚未配置 PostgreSQL，请填写 .env.local 并重启本地服务。':error?.code==='42P01'?'数据库表尚未创建，请先运行 npm run db:migrate。':'数据库连接或操作失败，请检查连接配置、网络和证书。编辑内容仍保留在浏览器。';return json({error:message},503);}
}
